# Generated by Django 4.2.2 on 2023-07-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_class',
            name='New_img',
            field=models.FileField(default=None, max_length=220, null=True, upload_to='news/'),
        ),
    ]
