# Generated by Django 4.2.2 on 2023-07-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('News', models.CharField(max_length=50)),
                ('Discription', models.CharField(max_length=50)),
            ],
        ),
    ]
