# Generated by Django 4.2.2 on 2023-07-03 07:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('News_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_class',
            name='Discription2',
            field=tinymce.models.HTMLField(default=None),
            preserve_default=False,
        ),
    ]
