# Generated by Django 4.2.2 on 2023-07-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News_App', '0002_model_class_discription2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_class',
            old_name='Discription',
            new_name='Discription1',
        ),
    ]
