# Generated by Django 4.2.2 on 2023-07-03 11:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('News_title', models.CharField(max_length=50)),
                ('News_discription', tinymce.models.HTMLField()),
            ],
        ),
    ]
