# Generated by Django 4.2.2 on 2023-07-04 10:45

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_class',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from=models.CharField(max_length=50), unique=True),
        ),
    ]
