# Generated by Django 4.2.2 on 2023-07-04 11:51

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_news', '0004_alter_model_class_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_class',
            name='slug',
        ),
        migrations.AddField(
            model_name='model_class',
            name='slug_data',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='News_title', unique=True),
        ),
    ]
