# Generated by Django 4.2.2 on 2023-07-05 04:43

import autoslug.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fild_title', models.CharField(max_length=50)),
                ('Fild_Discription', tinymce.models.HTMLField()),
                ('slug_data', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='News_title', unique=True)),
            ],
        ),
    ]
