# Generated by Django 4.2.2 on 2023-07-05 05:01

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Slug_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_class',
            name='slug_data',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Fild_title', unique=True),
        ),
    ]
