# Generated by Django 4.2.2 on 2023-07-04 09:48

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Filter_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_class',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='news_title', unique=True),
        ),
    ]
