# Generated by Django 4.2.2 on 2023-07-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bolock_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='field_Img',
            field=models.ImageField(default=None, upload_to=None),
            preserve_default=False,
        ),
    ]
