# Generated by Django 4.2.2 on 2023-07-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bolock_App', '0002_blog_field_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='field_Img',
            new_name='Img',
        ),
    ]
