# Generated by Django 4.2.2 on 2023-07-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bolock_App', '0003_rename_field_img_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Img',
            field=models.ImageField(height_field=230, max_length=200, upload_to='img', width_field=230),
        ),
    ]
