# Generated by Django 4.2.2 on 2023-07-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bolock_App', '0004_alter_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Img',
            field=models.FileField(default=None, max_length=220, null=True, upload_to='media/'),
        ),
    ]
