# Generated by Django 4.2.2 on 2023-07-07 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bolock_App', '0005_alter_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='release_date',
            field=models.DateField(default=datetime.date(2023, 7, 7)),
        ),
    ]
